// TypeScript file
let snowJson={
"texture":"snow.png",
"emitter":{"x":800,"y":-150}
,"maxRadiusVariance":30
,"minRadius":20
,"endBlue":255
,"minRadiusVariance":10
,"startSize":20
,"tangentialAcceleration":0
,"rotatePerSecond":30
,"startRedVariance":0
,"startBlue":255
,"rotatePerSecondVariance":10
,"endSize":10
,"emitterVariance":{"x":983,"y":0}
,"startGreen":255
,"gravity":{"x":10,"y":100}
,"startSizeVariance":25
,"startAlpha":0
,"endBlueVariance":0
,"engGreenVariance":0
,"emitAngleVariance":360
,"startGreenVariance":0
,"endSizeVariance":5
,"endAlphaVariance":0
,"endAlpha":1
,"emitAngle":128
,"startRotationVariance":45
,"startAlphaVariance":0
,"startRed":255
,"endRotation":360
,"startRotation":50
,"endRotationVariance":292.07
,"maxRadius":100
,"endGreen":255
,"endRed":255
,"speedVariance":0
,"maxParticles":200
,"emitterType":0
,"blendFactorSource":"one"
,"speed":64
,"radialAcceleration":0
,"blendFactorDestination":"oneMinusSourceAlpha"
,"radialAccelerationVariance":0
,"startBlueVariance":0
,"endRedVariance":0
,"lifespan":3500
,"tangentialAccelerationVariance":0
,"lifespanVariance":700
,"duration":-1
}
