// TypeScript file
var snowJson = {
    "texture": "snow.png",
    "emitter": { "x": 800, "y": -150 },
    "maxRadiusVariance": 30,
    "minRadius": 20,
    "endBlue": 255,
    "minRadiusVariance": 10,
    "startSize": 20,
    "tangentialAcceleration": 0,
    "rotatePerSecond": 30,
    "startRedVariance": 0,
    "startBlue": 255,
    "rotatePerSecondVariance": 10,
    "endSize": 10,
    "emitterVariance": { "x": 983, "y": 0 },
    "startGreen": 255,
    "gravity": { "x": 10, "y": 100 },
    "startSizeVariance": 25,
    "startAlpha": 0,
    "endBlueVariance": 0,
    "engGreenVariance": 0,
    "emitAngleVariance": 360,
    "startGreenVariance": 0,
    "endSizeVariance": 5,
    "endAlphaVariance": 0,
    "endAlpha": 1,
    "emitAngle": 128,
    "startRotationVariance": 45,
    "startAlphaVariance": 0,
    "startRed": 255,
    "endRotation": 360,
    "startRotation": 50,
    "endRotationVariance": 292.07,
    "maxRadius": 100,
    "endGreen": 255,
    "endRed": 255,
    "speedVariance": 0,
    "maxParticles": 200,
    "emitterType": 0,
    "blendFactorSource": "one",
    "speed": 30,
    "radialAcceleration": 0,
    "blendFactorDestination": "oneMinusSourceAlpha",
    "radialAccelerationVariance": 0,
    "startBlueVariance": 0,
    "endRedVariance": 0,
    "lifespan": 3500,
    "tangentialAccelerationVariance": 0,
    "lifespanVariance": 700,
    "duration": -1
};
//汉堡位置及其大小
var pointJson = {
    "0_0": { x: 506, y: 506, scale: 1 },
    "0_1": { x: 707, y: 506, scale: 1 },
    "0_2": { x: 919, y: 506, scale: 1 },
    "1_0": { x: 529, y: 406, scale: 0.78 },
    "1_1": { x: 687, y: 406, scale: 0.78 },
    "1_2": { x: 856, y: 406, scale: 0.78 },
    "2_0": { x: 541, y: 332, scale: 0.64 },
    "2_1": { x: 672, y: 332, scale: 0.64 },
    "2_2": { x: 801, y: 332, scale: 0.64 }
};
var coinJson = {
    "texture": "coin.png",
    "startAlphaVariance": 0,
    "maxRadiusVariance": 30,
    "tangentialAccelerationVariance": 0,
    "minRadius": 20,
    "endBlue": 255,
    "maxRadius": 100,
    "minRadiusVariance": 10,
    "startSize": 60,
    "tangentialAcceleration": 0,
    "rotatePerSecond": 30,
    "startSizeVariance": 20,
    "rotatePerSecondVariance": 10,
    "startAlpha": 0.8901960784313725,
    "startRedVariance": 0,
    "endSizeVariance": 10,
    "startBlue": 255,
    "emitAngle": 90,
    "emitter": { "x": 0, "y": 0 },
    "endSize": 40,
    "emitAngleVariance": 360,
    "endAlpha": 1,
    "startRotation": 0,
    "startGreenVariance": 0,
    "startRotationVariance": 45,
    "startBlueVariance": 0,
    "endRotation": 263.58,
    "endGreen": 255,
    "endRotationVariance": 292.07,
    "startGreen": 255,
    "endRedVariance": 0,
    "endBlueVariance": 0,
    "emitterVariance": { "x": 0, "y": 8 },
    "gravity": { "x": 50, "y": 1120 },
    "speedVariance": 0,
    "maxParticles": 500,
    "emitterType": 0,
    "blendFactorSource": "one",
    "speed": 500,
    "radialAcceleration": 0,
    "blendFactorDestination": "oneMinusSourceAlpha",
    "radialAccelerationVariance": 0,
    "engGreenVariance": 0,
    "startRed": 255,
    "endRed": 255,
    "lifespan": 2000,
    "endAlphaVariance": 0,
    "lifespanVariance": 700,
    "duration": 500
};
//# sourceMappingURL=PointSheet.js.map